#!/usr/bin/env bash
# vnnik2-20260915 build: fetch commit $1 of the jhan-amx-vnniK branch (from the NFS
# worktree) into /var/tmp/jhan/tron-vnnik2 on delphi-3bda, configure with
# TRON_AMX_DISPATCH=ON TRON_K_VNNI=ON BUILD_INGEST_MODELS=ON, syntax-check the two
# translation units that instantiate the new save_k code (fast failure), build runtron
# and the four unit tests on socket 1, run the tests, run the Haskell emitter tests,
# and copy gen/runtron to gen/runtron.vnnik2. The old vnni binary
# (/var/tmp/jhan/tron-vnnik/gen/runtron.vnnik, tip 5e45ae55ae) is left untouched as
# the control arm.
# Usage (on delphi-3bda): build.sh <commit>
set -u
COMMIT=$1
EXEC=/home/jhan/workspace/intel-AMX/exec
RES=${RES:-$EXEC/results/vnnik2-20260915}
LOG=${LOG:-$EXEC/logs/vnnik2-build.log}
SRC_WT=/home/jhan/workspace/intel-AMX/VNNIed-K-in-place/tron-VNNIed-K
WT=${WT:-/var/tmp/jhan/tron-vnnik2}
SUFFIX=${SUFFIX:-vnnik2}   # gen/runtron.$SUFFIX
OUR_CPUS=72-143,216-287
TESTS="t_k_vnni_layout t_amx_numerics t_amx_dispatch_dtype t_llama_unit"
NIX=/home/jhan/.nix-profile/bin/nix
mkdir -p "$RES" "$EXEC/logs"
source "$EXEC/lib-guard.sh"
export GUARD_EXCLUDE_USERS="jhan nobody positron packer bill"
ts() { date -u +%FT%TZ; }
exec >>"$LOG" 2>&1
echo "=== vnnik2 build of $COMMIT started $(ts) ==="
rm -f "$RES/build.done"
if [ ! -d "$WT/.git" ] && [ ! -f "$WT/.git" ]; then
  ( cd /home/jhan/workspace/tron-amx && git fetch -q "$SRC_WT" "$COMMIT" && git worktree add --detach "$WT" "$COMMIT" ) || { echo "$(ts) worktree add failed"; echo worktree-failed >"$RES/build.done"; exit 1; }
else
  ( cd "$WT" && git fetch -q "$SRC_WT" "$COMMIT" && git checkout -q --detach "$COMMIT" ) || { echo "$(ts) checkout failed"; echo checkout-failed >"$RES/build.done"; exit 1; }
fi
cd "$WT" || exit 1
echo "$(ts) worktree at $(git rev-parse HEAD) ($(git log -1 --format='%ci %s'))"
exec {LOCK_FD}>/var/tmp/jhan/3bda-campaign.lock
until flock -n "$LOCK_FD"; do echo "$(ts) campaign flock held; build waits"; sleep 30; done
t0=$(date +%s)
nice -n10 taskset -c $OUR_CPUS "$NIX" develop --command bash -c '
  set -o pipefail
  cmake --preset cross-avx512 -DBUILD_INGEST_MODELS=ON -DTRON_AMX_DISPATCH=ON -DTRON_K_VNNI=ON -DCMAKE_CXX_FLAGS= 2>&1 | tail -3 || exit 2
  echo "configure ok $(date -u +%T)"
  # the fuse3 header is generated by an external-project target; the syntax check needs it
  cmake --build gen --target libfuse3_external -j16 >/dev/null 2>&1 && echo "dep libfuse3_external ok $(date -u +%T)" || echo "dep libfuse3_external FAILED (continuing)"
  # fast failure: syntax-only compile of the two TUs that instantiate the new code
  for TU in t/t_k_vnni_layout.cpp t/t_llama_unit.cpp; do
    python3 - "$TU" <<PY > syn_cmd.sh
import json,sys,shlex
tu=sys.argv[1]; d=json.load(open("gen/compile_commands.json"))
e=next((e for e in d if e["file"].endswith("/"+tu)), None)
if e is None: print("echo no-compile-entry-for "+tu+"; exit 3"); sys.exit()
args=shlex.split(e["command"]); out=[]; skip=False
for a in args:
    if skip: skip=False; continue
    if a=="-o": skip=True; continue
    if a=="-c": continue
    out.append(a)
out.append("-fsyntax-only")
print("cd "+shlex.quote(e["directory"])+" && "+" ".join(shlex.quote(a) for a in out))
PY
    bash syn_cmd.sh 2>&1 | grep -E "error:|warning:" | grep -v unused-command-line-argument | head -40
    rc=${PIPESTATUS[0]}; echo "syntax $TU rc=$rc $(date -u +%T)"; [ $rc -eq 0 ] || exit 4
  done
  cmake --build gen --target runtron '"$TESTS"' -j96 2>&1 | grep -E "error|FAILED|warning: .*k_vnni|warning: .*save_k" | sed -n 1,80p
  exit ${PIPESTATUS[0]}'
rc=$?
echo "$(ts) build rc=$rc in $(( $(date +%s) - t0 )) s"
if [ $rc -ne 0 ]; then echo "build-failed rc=$rc" >"$RES/build.done"; exec {LOCK_FD}>&-; exit 1; fi
strings gen/runtron | grep -q 'ingested-qwen-3-4b-instruct-2507' || { echo "$(ts) qwen plugin MISSING"; echo no-qwen >"$RES/build.done"; exit 1; }
grep -c "save_k_helper" gen/src/tron/h/tron/plugins/qwen_3_4b_instruct_2507.hpp | sed 's/^/generated qwen plugin: save_k_helper calls = /'
grep -m1 "save_k<" gen/src/tron/h/tron/plugins/qwen_3_4b_instruct_2507.hpp | sed 's/^ */generated main call: /' | cut -c1-200
cp gen/runtron "gen/runtron.$SUFFIX"
{
  echo "tip $(git rev-parse HEAD) ($(git log -1 --format='%ci %s'))"
  echo "cmake --preset cross-avx512 -DBUILD_INGEST_MODELS=ON -DTRON_AMX_DISPATCH=ON -DTRON_K_VNNI=ON -DCMAKE_CXX_FLAGS= ; targets runtron $TESTS; built $(ts) in $(( $(date +%s) - t0 )) s on cpus $OUR_CPUS"
  sha256sum "gen/runtron.$SUFFIX"
  "./gen/runtron.$SUFFIX" --version 2>&1 | head -2
  echo "control binaries: /var/tmp/jhan/tron-vnnik/gen/runtron.vnnik (commit $(git -C /var/tmp/jhan/tron-vnnik rev-parse HEAD)), /var/tmp/jhan/tron-p0perf13/gen/runtron.p0perf13 (commit $(git -C /var/tmp/jhan/tron-p0perf13 rev-parse HEAD))"
  sha256sum /var/tmp/jhan/tron-vnnik/gen/runtron.vnnik /var/tmp/jhan/tron-p0perf13/gen/runtron.p0perf13
} >"$RES/build.txt"
cat "$RES/build.txt"
# unit tests (fake device; SYSTEM_CONFIG for the core set only)
fails=0; : >"$RES/tests.txt"
for t in $TESTS; do
  ( cd "$WT" && nice -n10 taskset -c $OUR_CPUS env SYSTEM_CONFIG="--instance 1,2" timeout -k 60 2400 "$WT/gen/$t" ) >"$RES/tests-$t.out" 2>&1
  trc=$?
  echo "$t rc=$trc tip=$COMMIT $(grep -E 'test cases:|All tests passed|FAILED|AMX unavailable' "$RES/tests-$t.out" | tr '\n' ' ' | cut -c1-300)" >>"$RES/tests.txt"
  [ $trc -eq 0 ] || fails=$((fails + 1))
done
cat "$RES/tests.txt"
# Haskell emitter tests
( cd "$WT/ingest" && nice -n10 taskset -c $OUR_CPUS "$NIX" develop --command bash -c 'cabal test 2>&1 | tail -15' ) >"$RES/cabal-test.out" 2>&1
hrc=$?
echo "cabal test rc=$hrc: $(grep -E 'examples|failures|passed|FAIL' "$RES/cabal-test.out" | tail -3 | tr '\n' ' ')" | tee -a "$RES/tests.txt"
[ $hrc -eq 0 ] || fails=$((fails + 1))
exec {LOCK_FD}>&-
echo "$([ $fails -eq 0 ] && echo ok || echo "tests-failed-$fails")" >"$RES/build.done"
echo "=== vnnik2 build finished $(ts): $(cat "$RES/build.done") ==="
