"""Report section assessing the supplied PDF against both pinned code revisions."""


def render(src, pdf, oldsrc):
  return f'''<section id="bill-note"><h2>Bill’s note: confirmed ideas and required adaptations</h2>
<p><strong>The PDF strengthens the architectural conclusion.</strong> It already proposes native blocked AVX on swizzled K, a direct source-layout-aware GOF shuffle, and a single persistent K with bounded unpacking for reference readers. It also records an AMD end-to-end regression and explicitly requires a GOF-cost measurement before removing the mirror. Those are useful additions to the design and its acceptance criteria. {pdf(7, 'PDF pp. 7–11')}.</p>
<p><strong>Its implementation baseline is different.</strong> The note identifies <code>bill-amx</code>, PR #2934 through <code>309168e2e</code>, and the related #2999 CI branch. This report still audits PR #3879 at <code>60d66d9c0442</code>. I retrieved the historical kernel headers from the exact <code>309168e2e90ef95dae4090344cad0ce53b1fdd1f</code> object locally to check the layout and dispatcher; that does not verify every later change described for #2999. The PDF’s branch status and CI prerequisites are historical statements, not current status checks. {pdf(3, 'PDF pp. 3–4')}.</p>
<div class="table-scroll"><table><thead><tr><th>Topic</th><th>Bill’s PDF / earlier branch</th><th>Application to PR #3879</th></tr></thead><tbody>
<tr><td>AVX reader</td><td>Already has blocked AVX-512 BF16 consuming the same K as its AMX kernel.</td><td>Confirms the instruction-level proposal. Port the token-lane algorithm using PR3879’s offsets; its current dotter still expects a contiguous row. {pdf(4, 'PDF p. 4')}; {oldsrc('h/tron/kernels/avx512_blocked_attention.hpp', 29)}.</td></tr>
<tr><td>Dispatcher and shapes</td><td>M-buckets: small dotter, blocked AVX, then AMX; head sizes 64/128; an AMD blocked tier and batched-query path.</td><td>PR3879’s AMX path is BF16 Q, head-128/GQA-4 and a full visible page. The older bucket thresholds and gpt-oss results do not describe this dispatcher. {pdf(13, 'PDF p. 13')}; {src('h/tron/kernels/amx_attn_iface.hpp', 133)}.</td></tr>
<tr><td>Mirror allocation</td><td>Third plane inside the DMA-backed KV block; head-size-only allocation can waste space on GQA-3.</td><td>PR3879 uses a separate ordinary-RAM arena, with model/runtime eligibility. Removing it saves that RAM; it does not automatically increase the current hugepage-backed page count. {pdf(5, 'PDF pp. 5–6')}; {src('h/tron/models/kv_cache.hpp', 555)}.</td></tr>
<tr><td>Storage eligibility</td><td>Format family chosen using <code>kv_mul</code>, not runtime query count M.</td><td>Keeping encoding stable is correct. PR3879 also permits different writer/reader ratios to share a physical slot, so the slot’s full consumer set must decide its encoding. Removing a second copy eliminates mirror coherence, not type, readiness or capability checks. {pdf(6, 'PDF pp. 6, 8')}; {src('h/tron/kernels/amx_attn_iface.hpp', 159)}.</td></tr>
<tr><td>Contiguous K inventory</td><td>Calls <code>k_at()</code> dead code with zero callers.</td><td>That deletion is unsafe in PR3879: row accessors and page-copy code actively call it. Migrate those users first. {pdf(7, 'PDF p. 7')}; {src('h/tron/models/kv_cache.hpp', 1574)}; {src('h/tron/models/kv_cache.hpp', 1961)}.</td></tr>
<tr><td>Build instructions</td><td><code>SW_ATTN_DISPATCH</code>, Delphi preset and #2999.</td><td>PR3879 has opt-in <code>TRON_AMX_DISPATCH</code>/<code>TRON_AMX_K_MIRROR</code>, isolated AMX compilation and a CI TODO for #3997. The PDF commands were not executed. {pdf(12, 'PDF p. 12')}; {src('src/tron/CMakeLists.txt', 166)}.</td></tr>
</tbody></table></div>
<h3>The two VNNI encodings have different panel orders</h3>
<p>Both put a dimension pair from each token into one 32-bit lane, but their page-wide ordering differs. For head-128, Bill’s older format is <code>[token block][dimension block][pair][token][2]</code>; PR3879’s mirror is <code>[dimension block][token block][pair][token][2]</code>. The two outer axes are exchanged. {oldsrc('h/tron/kernels/amx_kv_layout.hpp', 48)}; {src('h/tron/models/kv_cache.hpp', 640)}.</p>
<pre><code>// BF16 element offsets, p = token, d = dimension, P=64 and D=128.
Bill:   (p/16)*128*16 + (d/2)*32 + (p%16)*2 + d%2
PR3879: ((((d/32*4 + p/16)*16 + (d%32)/2)*16 + p%16)*2 + d%2)

Example K[0][32]: Bill offset = 512; PR3879 offset = 2048.</code></pre>
<p>Therefore the PDF’s simple pair-stride source expression must not be pasted into a PR3879 shuffle with one token-tile base. Pass the page base, token offset, geometry and encoding—or a typed equivalent—and apply the complete current offset function. Retaining PR3879’s format also retains its existing AMX panel offsets. Choosing Bill’s outer order instead would require updating the AMX reader too. {pdf(8, 'PDF p. 8')}; {src('src/tron/kernels/amx_attn.cpp', 249)}.</p>
<p>A new scalar address check confirmed that both formulas are bijections over 8,192 values, but 6,144 logical values have different physical offsets. Composing either correct decoder with the existing H=128 HBM permutation gave identical logical staging rows for all 64 tokens. This checks address algebra only; it does not execute the production shuffle or measure GOF latency. <a href="single-k-evidence/check_bill_layout.py">Check source</a>; <a href="single-k-evidence/bill-layout-check.json">result</a>.</p>
<h3>Direct GOF packing is the right target; negligible cost is unproven</h3>
<p>I adopt Bill’s preferred production design: change the source reads of the existing shuffle and write directly into the current GOF staging destination. There is no need for an additional contiguous K staging buffer. An unpack-then-old-shuffle path is useful as a test oracle or reference fallback, rather than the production target. Bill’s own step 3 makes a measured <code>gof_populate</code> comparison an early gate. {pdf(8, 'PDF pp. 8–10')}.</p>
<p>The operation count alone does not make the conversion free. A head-128 token spans four canonical cache lines, versus 64 swizzled lines. Four GOF tokens share those 64 lines only when their physical source placement permits it; cross-book or different token-block sources may touch more. A just-written row may be hot, but later backfill, staging reconstruction after eviction, and execution on another worker do not inherit that assumption. Even L1 hits leave load-uop and vectorization costs to measure. The report therefore retains an explicit first-fill, cold-rebuild and cross-book GOF performance gate. {pdf(10, 'PDF p. 10')}; {src('src/tron/gof.cpp', 140)}; {src('src/tron/gof.cpp', 193)}.</p>
<h3>What the historical measurements establish</h3>
<div class="table-scroll"><table><thead><tr><th>PDF-reported workload</th><th>Reported result</th><th>Interpretation here</th></tr></thead><tbody>
<tr><td>Granite Rapids, gpt-oss-120b-tp4, four users</td><td>2K/1K: 631.89 → 648.74 tok/s (+2.7%).<br>8K/1K: 514.92 → 670.35 tok/s (+30.2%).</td><td>Older dispatcher with a mirror, not a single-K result or PR3879 head-128 result.</td></tr>
<tr><td>Zen 4 EPYC 9654, llama-3-8B, four users, 2K/1K, eight FPGAs</td><td>724.0 → 676.2 tok/s (−6.6%), three interleaved runs.</td><td>Evidence in the note that a kernel win did not survive integration. It does not isolate how much removing the mirror would recover.</td></tr>
<tr><td>Zen 4, gpt-oss-120b</td><td>Measurement did not complete.</td><td>No AMD enablement conclusion follows from this document.</td></tr>
</tbody></table></div>
<p>These are attributed to {pdf(5, 'PDF p. 5')} and {pdf(11, 'p. 11')}; their raw benchmark logs were not supplied or independently reproduced in this update. The note attributes the AMD regression partly to mirror writes/cache pressure, while also naming unnecessary masked-column work and unchanged softmax/PV. A single-K change still performs the primary scatter and does not automatically fix the other costs. Its small-M dispatcher timings also differ in work from this report’s QK-only local proof; do not combine their speedup ratios.</p>
<h3>Preserve the intended deterministic reference behavior</h3>
<p>The PDF requires its <code>pay_for_determinism</code> mode to retain the reference path. Add that case explicitly to the migration tests. If that contract requires the old reduction tree, either select canonical storage before cache construction or unpack only the required rows into bounded scratch for the existing dotter; disabling AMX while using the new token-lane AVX kernel does not restore the old sum order. {pdf(11, 'PDF p. 11')}.</p>
<p>Do not infer an existing PR3879 scalar-dispatch gate from the PDF. The pinned PR checks AMX shape/type/availability and page density, while its determinism flag is used to stabilize worker planning. Its documented guarantee is repeatability under the same workload/hardware assumptions, not bitwise identity across all kernels or formats. Preserve those scheduling controls and explicitly decide whether the migration additionally needs reference-output compatibility. This is an integration requirement, not a claim that different deterministic arithmetic is inherently incorrect. {src('h/tron/models/self_attention.hpp', 1359)}; {src('h/tron/models/model.hpp', 2021)}; {src('h/runtron/stream_generate.hpp', 180)}.</p>
</section>'''
