#!/usr/bin/env python3
"""P1a spike patcher: make the router gate matmul CPU-computable in the
GENERATED ingested_gpt_oss_20b.hpp, gated by TRON_CPU_ROUTER at runtime.

Design (from the recon, exec/results/router/P1A-preregistration.md Phase S):
- dual members: ADD tensor<32,2880> <name>_host next to each dtensor member
  (launcher/channel types key on the executor alias, so the device member
  stays; 24 layers);
- twin visit() per weight so the NORMAL loader fills the host copy from the
  same checkpoint tensor (BF16 -> fp32 by assignment dispatch);
- fill/prepare sites: device-only via if (!cpu_router); CPU mode records the
  layer's host-weight pointer for the launch site;
- launch block (textually identical across layers): if (cpu_router) run the
  synchronous CPU router (compute + sentinel-safe publish + the same
  finish_writing/finish_reading callback inline) else the existing block;
- sentinel contract: bf16 elements 0..27 stored first, elements 28..31
  composed into one uint64_t released-stored last (the channel latch watches
  those 8 bytes; torn stores would release the latch on NaN logits);
- marker comment block: spike artifact, never a golden baseline.

Idempotent: refuses to run if the marker is already present.
Hard-asserts every replacement count == 24.
"""
import re
import sys

HDR = "/home/jhan/workspace/tron-router-p0/gen/src/tron/h/tron/plugins/ingested_gpt_oss_20b.hpp"

MARKER = """\
// ============================================================================
// SPIKE ARTIFACT - HAND-EDITED GENERATED FILE (P1a type-feasibility spike)
// ============================================================================
// This file was generated by the ingest pipeline and then HAND-EDITED by
// exec/r0-p1a-patch-header.py (intel-AMX repo) to add a TRON_CPU_ROUTER
// runtime branch: router gate logits computed on the CPU from a host fp32
// copy of the weight. It exists ONLY in the tron-router-p0 worktree.
// NEVER use this file as a baseline for anything - in particular not for the
// generator golden test (plan sec 5), whose baseline is pristine emitter
// output. Pre-registration: exec/results/router/P1A-preregistration.md.
// ============================================================================
"""

CPU_STATIC = """\
  // SPIKE: runtime switch for the CPU router branch (see marker block above).
  inline static const bool cpu_router = [] {
    const char* e = std::getenv("TRON_CPU_ROUTER");
    return e && *e && !(e[0] == '0' && !e[1]);
  }();
"""

HELPER = """\
    // SPIKE: layer's host router weight, set at the fill/prepare site in CPU
    // mode, consumed at the launch site (fill and launch are separate
    // generated statements).
    const tensor<32, 2880>* cpu_router_w = nullptr;
    // SPIKE: lazy per-layer bf16 copy of the host router weight for the
    // vdpbf16ps kernel (the checkpoint is BF16, so the fp32 load round-trips
    // exactly). Driving-thread only - no locking.
    std::unordered_map<const void*, std::vector<bf16>> spike_wbf16;
    // SPIKE: the P0b avx_bf16 arm (6 accumulators, K=2880 = 15 x 192).
    // Requires avx512_bf16 at runtime (Granite Rapids) - spike-only, would
    // SIGILL on older hosts; acceptable for the tron-router-p0 worktree.
    __attribute__((target("avx512f,avx512bw,avx512vl,avx512bf16")))
    static void spike_router_logits(const bf16* w, const bf16* a, float* out) {
      for (size_t j = 0; j < 32; j++) {
        const bf16* wr = w + j * 2880;
        __m512 s0 = _mm512_setzero_ps(), s1 = s0, s2 = s0, s3 = s0, s4 = s0, s5 = s0;
        for (size_t k = 0; k < 2880; k += 192) {
          s0 = _mm512_dpbf16_ps(s0, (__m512bh)_mm512_loadu_si512(a + k),
                                (__m512bh)_mm512_loadu_si512(wr + k));
          s1 = _mm512_dpbf16_ps(s1, (__m512bh)_mm512_loadu_si512(a + k + 32),
                                (__m512bh)_mm512_loadu_si512(wr + k + 32));
          s2 = _mm512_dpbf16_ps(s2, (__m512bh)_mm512_loadu_si512(a + k + 64),
                                (__m512bh)_mm512_loadu_si512(wr + k + 64));
          s3 = _mm512_dpbf16_ps(s3, (__m512bh)_mm512_loadu_si512(a + k + 96),
                                (__m512bh)_mm512_loadu_si512(wr + k + 96));
          s4 = _mm512_dpbf16_ps(s4, (__m512bh)_mm512_loadu_si512(a + k + 128),
                                (__m512bh)_mm512_loadu_si512(wr + k + 128));
          s5 = _mm512_dpbf16_ps(s5, (__m512bh)_mm512_loadu_si512(a + k + 160),
                                (__m512bh)_mm512_loadu_si512(wr + k + 160));
        }
        out[j] = _mm512_reduce_add_ps(_mm512_add_ps(
            _mm512_add_ps(s0, s1),
            _mm512_add_ps(_mm512_add_ps(s2, s3), _mm512_add_ps(s4, s5))));
      }
    }
    // SPIKE: synchronous CPU router matmul. Publishes into linear_8 honoring
    // the channel latch's sentinel contract: the latch watches the LAST 8
    // bytes of each token's 32xbf16 payload (nans-armed by prepare()); those
    // bytes must change only after elements 0..27 are visible, in one store.
    void cpu_router_matmul(plugin_batch* q_batch) {
      {
        TRACE_EVENT("model", "cpu router compute");
        for (size_t task = 0; task < q_batch->items.size(); task++) {
          q_batch->rmsnorm_channel.start_reading_at(task);
          token_job_id ix = q_batch->items[task];
          float acc[32];
          auto& act = rmsnorm[ix];
          if constexpr (requires { act.data.get(); }) {
            // bf16 DMA activations (tp executors): the P0b avx_bf16 kernel.
            auto& wb = spike_wbf16[cpu_router_w];
            if (wb.empty()) {
              wb.resize(32 * 2880);
              for (size_t j = 0; j < 32; j++)
                for (size_t k = 0; k < 2880; k++)
                  wb[j * 2880 + k] = bf16((*cpu_router_w).data[j][k]);
            }
            spike_router_logits(wb.data(), act.data.get(), acc);
          } else {
            // host executor (fp32 activations): generic dot, correctness only.
            for (size_t j = 0; j < 32; j++) {
              acc[j] = dot((*cpu_router_w).data[j], act);
            }
          }
          auto& out = linear_8[ix];
          if constexpr (requires { out.data.get(); }) {
            // bf16 DMA payload: the channel latch watches the last 8 bytes -
            // store elements 0..27 first, then 28..31 as one released word.
            bf16* dst = out.data.get();
            for (size_t j = 0; j < 28; j++) dst[j] = bf16(acc[j]);
            bf16 tail[4] = {bf16(acc[28]), bf16(acc[29]), bf16(acc[30]), bf16(acc[31])};
            uint64_t word;
            __builtin_memcpy(&word, tail, 8);
            std::atomic_thread_fence(std::memory_order_release);
            *reinterpret_cast<volatile uint64_t*>(dst + 28) = word;
          } else {
            // host-executor payload (plain fp32 tensor, whole-phase fallback
            // latch): ordinary stores suffice.
            for (size_t j = 0; j < 32; j++) out.data[j] = acc[j];
          }
        }
      }
      {
        TRACE_EVENT("model", "cpu router publish");
      }
    }
"""

LAUNCH_OLD = """\
      {
        {
          TRACE_EVENT("model", "await deps mlp_router_weight_launcher");
          q_batch->linear_channel_5.start_writing(0);
          q_batch->rmsnorm_channel.start_reading(0);
        }
        {
          TRACE_EVENT("model", "launch mlp_router_weight_launcher");
          q_batch->mlp_router_weight_launcher([q_batch]() {
            q_batch->linear_channel_5.finish_writing(0);
            q_batch->rmsnorm_channel.finish_reading(0);
          });
        }
      }
"""

LAUNCH_NEW = """\
      if (cpu_router) {  // SPIKE branch
        {
          TRACE_EVENT("model", "await deps mlp_router_weight_launcher");
          q_batch->linear_channel_5.start_writing(0);
          q_batch->rmsnorm_channel.start_reading(0);
        }
        cpu_router_matmul(q_batch);
        q_batch->linear_channel_5.finish_writing(0);
        q_batch->rmsnorm_channel.finish_reading(0);
      } else {
        {
          TRACE_EVENT("model", "await deps mlp_router_weight_launcher");
          q_batch->linear_channel_5.start_writing(0);
          q_batch->rmsnorm_channel.start_reading(0);
        }
        {
          TRACE_EVENT("model", "launch mlp_router_weight_launcher");
          q_batch->mlp_router_weight_launcher([q_batch]() {
            q_batch->linear_channel_5.finish_writing(0);
            q_batch->rmsnorm_channel.finish_reading(0);
          });
        }
      }
"""


def main():
    src = open(HDR).read()
    if "SPIKE ARTIFACT" in src:
        print("refusing: header already carries the spike marker")
        sys.exit(1)
    n0 = len(src)

    # 1. marker block at the very top + <cstdlib>/<atomic> includes after the
    #    first include block line (the generated file starts with includes).
    first_inc = src.index("#include")
    src = src[:first_inc] + MARKER + "#include <atomic>\n#include <cstdlib>\n#include <immintrin.h>\n#include <unordered_map>\n#include <vector>\n" + src[first_inc:]

    # 2. cpu_router static after the is_host line.
    m = re.search(r"(inline static const bool wcls_is_compensated[^\n]*\n)", src)
    assert m, "wcls_is_compensated anchor not found"
    src = src[: m.end()] + CPU_STATIC + src[m.end():]

    # 3. host member decls next to each device decl.
    decl_re = re.compile(
        r"([ \t]*)dtensor_t<32, 2880> (mlp_router_weight\w*)\{uninitialized\};")
    decls = decl_re.findall(src)
    assert len(decls) == 24, f"expected 24 weight decls, found {len(decls)}"
    src, n = decl_re.subn(
        lambda mm: (f"{mm.group(0)}\n{mm.group(1)}tensor<32, 2880> "
                    f"{mm.group(2)}_host{{uninitialized}};  // SPIKE"),
        src)
    assert n == 24

    # 4. twin visit() lines (same placement-request name -> same checkpoint
    #    tensor through the normal loader).
    visit_re = re.compile(
        r"([ \t]*)visit\((mlp_router_weight\w*), (hardware::tensor_placement_request\{\"[^\"]*\"\})\);")
    src, n = visit_re.subn(
        lambda mm: (f"{mm.group(0)}\n{mm.group(1)}visit({mm.group(2)}_host, "
                    f"{mm.group(3)});  // SPIKE"),
        src)
    assert n == 24, f"expected 24 visit sites, found {n}"

    # 5. fill/prepare pairs: device-only + record the layer's host weight.
    fp_re = re.compile(
        r"([ \t]*)dtensor_t<32, 2880>::fill_matmul_template\(linear_8, rmsnorm, "
        r"q_batch->items, q_batch->mlp_router_weight_launcher, "
        r"q_batch->rmsnorm_channel\.waitable\(\), \"(mlp_router_weight\w*)\"\);\n"
        r"[ \t]*model\.(mlp_router_weight\w*)\.prepare_matmul\(q_batch->mlp_router_weight_launcher\);")

    def fp_sub(mm):
        ind, label, member = mm.group(1), mm.group(2), mm.group(3)
        assert label == member, f"label/member mismatch: {label} vs {member}"
        return (f"{ind}if (cpu_router) {{ cpu_router_w = &model.{member}_host; }} else {{  // SPIKE\n"
                f"{ind}  dtensor_t<32, 2880>::fill_matmul_template(linear_8, rmsnorm, "
                f"q_batch->items, q_batch->mlp_router_weight_launcher, "
                f"q_batch->rmsnorm_channel.waitable(), \"{label}\");\n"
                f"{ind}  model.{member}.prepare_matmul(q_batch->mlp_router_weight_launcher);\n"
                f"{ind}}}")

    src, n = fp_re.subn(fp_sub, src)
    assert n == 24, f"expected 24 fill/prepare pairs, found {n}"

    # 6. branch the 24 identical launch blocks.
    n = src.count(LAUNCH_OLD)
    assert n == 24, f"expected 24 launch blocks, found {n}"
    src = src.replace(LAUNCH_OLD, LAUNCH_NEW)

    # 7. helper + pointer member: insert right after the linear_8 declaration.
    anchor = re.search(
        r"([ \t]*indexed_vector<token_job_id, btensor_t<32>> linear_8;\n)", src)
    assert anchor, "linear_8 declaration anchor not found"
    src = src[: anchor.end()] + HELPER + src[anchor.end():]

    open(HDR, "w").write(src)
    print(f"patched {HDR}: {n0} -> {len(src)} bytes; 24 decls, 24 visits, "
          f"24 fill/prepare, 24 launch blocks, helper installed")


if __name__ == "__main__":
    main()
