import os,re,json,glob,datetime,sys
from zoneinfo import ZoneInfo
PT=ZoneInfo('America/Los_Angeles'); HOST=os.uname().nodename
NB='/home/jhan/workspace/notebook'; STORE=os.path.expanduser('~/.claude/projects')
# ---- handoffs
hand=[]
for f in sorted(glob.glob(f'{NB}/handoffs/*.md')):
    txt=open(f,encoding='utf-8',errors='replace').read()
    head=txt[:6000]
    sessions=re.findall(r'^- Claude session: "(.*?)"', head, re.M)
    chats=re.findall(r'^- Claude chat: "(.*?)"', head, re.M)
    trans=re.findall(r'Transcript: ([\w.-]+):(\S+?\.jsonl)', head)
    act=re.search(r'Activity dates: (\d{4}-\d{2}-\d{2})(?: to (\d{4}-\d{2}-\d{2}))?', head)
    gen=re.search(r'Generated by (\w+)', head)
    hand.append(dict(file=os.path.basename(f), tool=('claude' if os.path.basename(f).startswith('claude_') else 'codex' if os.path.basename(f).startswith('codex_') else 'other'),
        sessions=sessions, chats=chats, transcripts=[{'host':h,'path':p} for h,p in trans],
        start=act.group(1) if act else None, end=(act.group(2) or act.group(1)) if act else None, generated_by=gen.group(1) if gen else None))
# ---- local sessions
sess=[]
for pdir in sorted(glob.glob(f'{STORE}/*/')):
    proj=os.path.basename(pdir.rstrip('/'))
    for jf in sorted(glob.glob(pdir+'*.jsonl')):
        sid=os.path.basename(jf)[:-6]
        titles=[]; cwd=None; first=None; last=None; nuser=0; nasst=0; last_types=[]; first_user=None; lastuser_ts=None
        try:
            with open(jf,encoding='utf-8',errors='replace') as fh:
                for line in fh:
                    try: r=json.loads(line)
                    except Exception: continue
                    t=r.get('type')
                    if t=='custom-title': titles.append(('custom',r.get('customTitle'),r.get('timestamp')))
                    elif t=='ai-title': titles.append(('ai',r.get('aiTitle') or r.get('title'),r.get('timestamp')))
                    if cwd is None and r.get('cwd'): cwd=r['cwd']
                    ts=r.get('timestamp')
                    if ts and t in ('user','assistant'):
                        first=first or ts; last=ts
                        if t=='user':
                            nuser+=1
                            c=r.get('message',{}).get('content')
                            s=c if isinstance(c,str) else ' '.join(x.get('text','') for x in c if isinstance(x,dict)) if isinstance(c,list) else ''
                            if first_user is None and s and not s.startswith('<'): first_user=s[:160]
                            last_types.append(('user', s[:80]))
                        else:
                            nasst+=1; last_types.append(('assistant',''))
        except Exception as e:
            pass
        def pt(ts):
            if not ts: return None
            d=datetime.datetime.fromisoformat(ts.replace('Z','+00:00')).astimezone(PT); return d.strftime('%Y-%m-%d')
        # newest title wins
        title=None; source=None
        for kind,val,ts in titles:
            if val: title, source = val, kind
        sess.append(dict(project=proj, session_id=sid, path=jf, cwd=cwd, title=title, title_source=source, titles=[(k,v) for k,v,_ in titles],
            start=pt(first), end=pt(last), last_ts=last, n_user=nuser, n_assistant=nasst, first_user=first_user,
            excluded=bool(cwd and (cwd.startswith('/home/jhan/self/ai') or proj=='-home-jhan-self-ai')),
            size=os.path.getsize(jf), last_user_msgs=[m for k,m in last_types if k=='user'][-3:]))
json.dump(dict(host=HOST,handoffs=hand,sessions=sess),open(sys.argv[1],'w'),indent=1)
# ---- reconcile
bypath={s['path']:s for s in sess}
report=dict(update=[],unchanged=[],frozen=[],missing_transcript=[],rename=[],new=[],excluded_sessions=[],excluded_handoffs=[],codex=[],no_transcript_line=[])
covered=set()
for h in hand:
    if h['tool']!='claude': report['codex'].append(h['file']); continue
    if not h['transcripts']: report['no_transcript_line'].append(h['file']); continue
    for t in h['transcripts']:
        if t['host']!=HOST: report['frozen'].append((h['file'],t['host'])); continue
        s=bypath.get(t['path'])
        if not s: report['missing_transcript'].append((h['file'],t['path'])); continue
        covered.add(s['path'])
        if s['excluded']: report['excluded_handoffs'].append(h['file']); continue
        if s['title'] and h['sessions'] and s['title'] not in h['sessions']: report['rename'].append((h['file'],h['sessions'],s['title']))
        if s['end'] and h['end'] and s['end']>h['end']: report['update'].append((h['file'],h['end'],s['end'],s['n_user'],s['last_user_msgs']))
        else: report['unchanged'].append(h['file'])
for s in sess:
    if s['path'] in covered: continue
    if s['excluded']: report['excluded_sessions'].append((s['project'],s['title'],s['n_user'])); continue
    report['new'].append(dict(project=s['project'],title=s['title'],src=s['title_source'],start=s['start'],end=s['end'],n_user=s['n_user'],size=s['size'],path=s['path'],first_user=s['first_user'],cwd=s['cwd']))
json.dump(report,open(sys.argv[2],'w'),indent=1)
print(f"handoffs: {len(hand)} (claude {sum(1 for h in hand if h['tool']=='claude')}, codex {len(report['codex'])})")
print(f"local sessions: {len(sess)} in {len(set(s['project'] for s in sess))} projects; excluded {len(report['excluded_sessions'])}")
for k in ('update','unchanged','frozen','missing_transcript','rename','new','excluded_handoffs','no_transcript_line'): print(f"  {k}: {len(report[k])}")
print("\n-- UPDATE candidates (file, END, newest activity, n_user, last user msgs):")
for u in report['update']: print(' ',u[0],u[1],'->',u[2],'|',u[3],'|',[m[:50] for m in u[4]])
print("\n-- RENAME candidates:"); [print(' ',r) for r in report['rename']]
print("\n-- NEW candidates (project | title [src] | dates | n_user | KB):")
for n in sorted(report['new'],key=lambda x:(x['project'],x['start'] or '')): print(f"  {n['project']} | {n['title']!r} [{n['src']}] | {n['start']}..{n['end']} | {n['n_user']} | {n['size']//1024} | {(n['first_user'] or '')[:70]!r}")
print("\n-- FROZEN hosts:", sorted(set(h for _,h in report['frozen'])), len(report['frozen']))
print("-- missing transcripts:", len(report['missing_transcript']))
