import re,sys
p='gen_ben.py'; s=open(p).read()
n=0
def rep(old,new,count=1):
    global s,n
    if old not in s:
        print("MISSING:", old[:100]); sys.exit(1)
    s=s.replace(old,new,count); n+=1
rep('then 4133869073 (27 minutes later)','then 4133869073 (10 minutes later)')
rep('PR 4557 head (main + 10)','PR 4557 head (main + 12)')
rep('<li>The three other DMA factories (make_unique_dma at memory.hpp:239 and :254, make_unique_dma_for_overwrite at :274 and :286) still call dma_allocate_aligned directly and use std::memset, which creates no objects either. Direct callers',
    '<li>The four other DMA factories (the two make_unique_dma overloads at memory.hpp:239 and :254, the two make_unique_dma_for_overwrite overloads at :274 and :286) still call dma_allocate_aligned directly. The make_unique_dma pair also zero-fills with std::memset (:241, :257), which creates no objects either. Direct callers')
rep('only the stride 1 in <code>sseq&lt;1&gt;</code> inside the two aliases, the same spelling native_k_view uses in kv_cache_fwd.hpp.',
    'only the stride 1 in <code>sseq&lt;1&gt;</code> inside the two aliases. native_k_view in kv_cache_fwd.hpp writes the same bare stride literal as <code>std::integer_sequence&lt;ptrdiff_t, Cols, 1&gt;</code>.')
rep('They are used on 31 PR-added lines in 9 files. main has 0 uses','They appear on 31 PR-added lines in 9 files: the 2 definitions and 29 uses. main has 0 uses')
rep('("Uses of VIEW_ALIGNED_TRUE / VIEW_DMA_FALSE", "0", "31 lines, 9 files")','("Lines with VIEW_ALIGNED_TRUE / VIEW_DMA_FALSE (2 definitions + 29 uses)", "0", "31 lines, 9 files")')
rep('("call sites passing bare true / false to a view", "82 lines, 80 sites, 20 files", "0")','("lines that spell a view type with a bare true or false (grep (const_)?views?<[^;{]*(true|false) over h, src, t, plus the 4 continuation lines in dmatensor.hpp; a stricter pattern that needs a true/false pair on one line gives 75 lines in 19 files)", "82 lines, 80 sites, 20 files", "0")')
rep('<text x="10" y="312" class="m">Total 137 declaration lines at main. Plus 82 call-site lines in 20 files that pass bare true/false,</text>','<text x="10" y="312" class="m">Total 137 declaration lines at main. Plus 82 call-site lines in 20 files that spell a view with bare true/false,</text>')
rep('a("<p>Timeline of 2026-09-29 (UTC): 12:47 to 13:35 the six comments are drafted. 13:43 the reviewer commits the fix that became #4698. 13:45 he commits the helper change that became #4697. 14:01 #4697 opens. 14:44 #4698 opens. 14:56 the review is submitted as CHANGES_REQUESTED, and a second review (5354385317) adds the \\"not a blocker\\" note on B1. So the B4 comment was written 13 minutes before its own fix existed, and no comment mentions #4698.</p>")',
    'a("<p>Timeline of 2026-09-29 (UTC):</p><ul><li>12:47 to 13:35: five of the six comments (B1 to B5) are drafted.</li><li>13:43: the reviewer commits the fix that became #4698.</li><li>13:45: he commits the helper change that became #4697.</li><li>14:01: #4697 opens. 14:44: #4698 opens.</li><li>14:56: he writes B6 (the comment that points at #4697) and submits the review as CHANGES_REQUESTED. A second review (5354385317) adds the \\"not a blocker\\" note on B1.</li></ul><p>So the B4 comment was written 13 minutes before its own fix existed. No comment mentions #4698.</p>")')
rep('a("<li>#4697 CI: Build Tron, Test host, Test FPGA, Lint and the rest pass (2026-09-29). #4698 CI: 21 of 21 check rows pass, including a Benchmark row on andoria-14 (an AMD host: same-host comparison shows no regression; the cross-host comparison flags one llama tp4 row at -2.1 % against a baseline from another machine, which is not a like-for-like measurement).</li>")',
    'a("<li>#4697 CI: Build Tron, Test host, Test FPGA, Lint and the rest pass (2026-09-29). #4698 CI: 21 of 21 check rows pass. One row is a Benchmark on andoria-14 (an AMD host without AMX). Its same-host comparison shows no regression. Its cross-host comparison marks two llama rows as regressions against a baseline from another machine (andoria-09): llama-3.1-8b tp4 (tensor parallel over 4 cards) at -2.1 % generate tokens per second and -2.1 % parse tokens per second, and llama-3.1-8b tp2 parse at -1.6 %. A cross-host comparison is not a like-for-like measurement.</li>")')
rep('#4698 conflicts with the B4 fallback commit (the one-line issue reference), because #4698 deletes the paragraph that line extends [git merge-tree, 1 marker].</li>',
    '#4698 conflicts with the B4 fallback commit (the one-line issue reference). The reason: #4698 deletes the paragraph that the one line extends [git merge-tree, 1 marker].</li>')
rep('The 3bda runs in section 10 close that gap for #4697; the r2 run closes it for #4698.</li>','The r1 runs in section 10 close that gap for #4697. The r2 run (section 10) covers #4698.</li>')
rep('A fast-forward keeps the reviewer\'s commit id and lets GitHub mark his PR as merged.','A fast-forward keeps the reviewer\'s commit id and should let GitHub mark his PR as merged (not exercised, section 13).')
rep('then push. CI runs.</li>")','then push. CI runs. PR #4557 carries the label \\"Skip benchmarks\\", so that run has no Benchmark row unless the label is removed first (<code>gh pr edit 4557 --remove-label \\"Skip benchmarks\\"</code>).</li>")')
rep('a("<li><strong>Post the six replies</strong> (drafts in sections 4 to 9, commit ids filled in) under comments 4134933234 (B1), 4133643149 (B2), 4133869073 (B3), 4134028988 (B4), 4134076112 (B5), 4134925164 (B6).</li>")\n    a("<li><strong>File the B1 follow-up issue</strong> (draft in section 4) before posting the B1 reply, and paste its URL into the reply. No names in the issue.</li>")',
    'a("<li><strong>File the B1 follow-up issue</strong> (draft in section 4) and keep its URL for the B1 reply. No names in the issue.</li>")\n    a("<li><strong>Post the six replies</strong> (drafts in sections 4 to 9, commit ids and the issue URL filled in) under comments 4134933234 (B1), 4133643149 (B2), 4133869073 (B3), 4134028988 (B4), 4134076112 (B5), 4134925164 (B6).</li>")')
rep('(no git commands inside it: it shares the admin dir of the rt2 worktree)','(run no git commands inside it: it shares the git administrative directory, the .git metadata, with /var/tmp/jhan/tron-i4525rt2, an earlier 3bda checkout of this branch)')
rep('Land the follow-up after #4557, #4697 and with an eye on #4424.','Land the follow-up after #4557 and #4697, and coordinate it with #4424.')
rep('So the enum change should land after #4697, which I am taking into this branch first.','So the enum change should land after #4697. I am taking #4697 into this branch first.')
rep("`view` and `const_view` take their two flags as `bool` template parameters. Call sites pass bare `true, false` (82 lines in 20 files) and can swap the two flags without a compile error. This issue replaces the two `bool` parameters with two enum types, so that swapped or bare arguments fail to compile. PR #4557 added two named constants as a stop-gap. This follow-up removes them.",
    "`view` and `const_view` take their two flags as `bool` template parameters, and call sites can swap the two flags without a compile error (82 lines in 20 files pass bare `true, false`). This issue replaces the two `bool` parameters with two enum types, so that swapped or bare arguments fail to compile. PR #4557 added two named constants as a temporary measure, and this follow-up removes them.")
rep("- `aligned` flag: `true` means the data pointer is aligned for whole-register loads, so chunked SIMD reads are allowed.\n- `dma` flag: `true` means the memory is DMA-safe (usable by the accelerator cards). The flag takes part in type identity only. No code branches on it.",
    "- `aligned` flag: `true` means the data pointer is aligned for whole-register loads, so chunked SIMD (single instruction, multiple data: one instruction on a whole register) reads are allowed.\n- `dma` flag: `true` means the memory is DMA-safe (direct memory access: usable by the accelerator cards). The flag takes part in type identity only. No code branches on it.")
rep('I applied it by hand rather than through the suggestion button, because 15 other comments reference the title.','I applied it by hand rather than through the suggestion button. The button would have renamed the header only, and 15 other comments reference the title.')
rep('the header and its underline in v_vnni.hpp, and 15 references','the header line in v_vnni.hpp and 15 references')
rep('The old kv_block was an aggregate of bf16s arrays, an implicit-lifetime type. The new kv_block is still an aggregate, and v_vnni_tensor has a trivial implicit default constructor and a trivial destructor, so it is an implicit-lifetime class by [class.prop]/9. The static_assert on kv_block::v_storage [kv_cache.hpp:2455-2458] and the two in the accessors [:1554-1557, :1597-1600] pin those traits (16-lane build; the 8-lane build keeps a bf16s array with no assert).',
    'The old kv_block was an aggregate of bf16s arrays, an implicit-lifetime type. The new kv_block is still an aggregate. v_vnni_tensor has a trivial implicit default constructor and a trivial destructor. So it is an implicit-lifetime class by [class.prop]/9. The static_assert on kv_block::v_storage [kv_cache.hpp:2455-2458] and the two in the accessors [:1554-1557, :1597-1600] pin those traits in the 16-lane build. The 8-lane build keeps a bf16s array with no assert.')
rep('(iii) Previously okay because the storage held POD, but now','(iii) Previously okay because the storage held POD (plain old data: a type with no constructor logic), but now')
rep("A function named operator new or operator new[] is one of several operations that create objects without a constructor call. N4950 [intro.object]/13 and its note also list malloc and its relatives, memcpy/memmove, bit_cast, std::start_lifetime_as, and starting the lifetime of an unsigned char or std::byte array. The Note\\'s point",
    "A function named operator new or operator new[] is one of several operations that create objects without a constructor call. N4950 [intro.object]/13 also names starting the lifetime of an unsigned char or std::byte array. Its note points to the library operations that do the same: malloc and its relatives ([c.malloc]), memcpy/memmove ([cstring.syn]), bit_cast ([bit.cast]), std::start_lifetime_as ([obj.lifetime]) and allocator_traits::allocate ([allocator.traits.members]). The Note\\'s point")
rep('("for example scalars, arrays, and classes with a trivial constructor and destructor.", "Numbers and pointers, arrays of anything on this list, and classes whose default constructor and destructor do nothing.',
    '("for example scalars, arrays, and classes with a trivial constructor and destructor.", "Numbers and pointers, arrays of any type, and classes whose default constructor and destructor do nothing.')
rep('a("<p>Every sentence is right. What the reviewer hit is density: the first sentence states a rule most C++ readers have never met, without saying what goes wrong without it, and the [class.prop] citation is narrower than the claim. The reword below keeps every fact, adds the mechanism (what the KV book does, what goes wrong), and glosses the standard terms once.</p>")',
    'a("<p>Every sentence is right. The problem is density. The first sentence states a rule most C++ readers have never met, and it does not say what goes wrong without the rule. The [class.prop] citation is narrower than the claim. The reword below keeps every fact, adds the mechanism (what the KV book does, what goes wrong), and explains the standard terms once.</p>")')
rep('a("<p>Changes from the version the workflow first applied: the sentence \\"Compiler warnings and sanitizers do not catch it.\\" was dropped. A refuter measured it on a 17-line sample with GCC 14.3 and 11.4 (-Wall -Wextra -Wpedantic silent, ASan and UBSan clean), but clang was not measured, and the Note does not need the claim. The reply carries the measurement instead. Spelling: \\"behavior\\", the codebase\'s only spelling. Every line is at or under 80 columns (the old text had one 83-column line; the repo limit is 88, so that was never a violation).</p>")',
    'a("<p>Changes from the version the workflow first applied (commit 2ebc426f3d):</p><ul><li>The sentence \\"Compiler warnings and sanitizers do not catch it.\\" was dropped. A refuter measured it on a 17-line sample with GCC 14.3 and 11.4: -Wall -Wextra -Wpedantic silent, ASan and UBSan clean (AddressSanitizer and UndefinedBehaviorSanitizer, two run-time checkers built into the compiler). clang was not measured. The Note does not need the claim, and the reply carries the measurement instead.</li><li>Three wordings tightened after the standard check of this page: objects that no code constructs (not all objects of those types) come only from the listed operations. std::start_lifetime_as (C++23) is on the list. Each operation creates the objects in its own region (the memory it returns, the destination it fills, or the byte array itself). dma_allocate_aligned calls none of them.</li><li>Spelling: \\"behavior\\", the codebase\'s only spelling.</li><li>Every line is at or under 80 columns. The old text had one 83-column line. The repo limit is 88, so that was never a violation.</li></ul>")')
rep('Filing it is jhan\'s call.','Filing it is jhan\'s decision.')
rep('GCC 14.3 with -Wall -Wextra gives no warning on a small sample of that pattern, and ASan/UBSan run it clean. I did not measure clang.','GCC 14.3 and 11.4 with -Wall -Wextra -Wpedantic give no warning on a 17-line sample of that pattern, and ASan/UBSan (AddressSanitizer and UndefinedBehaviorSanitizer) run it clean. I did not measure clang.')
rep("- `operator new` is one item on the list, not the only one. [intro.object]/13 and its note also list `malloc` and its relatives, `memcpy`/`memmove`, `bit_cast`, and starting the lifetime of a `std::byte` array. `dma_allocate_aligned` is on none of these lists.",
    "- `operator new` is one item on the list, not the only one. [intro.object]/13 also names starting the lifetime of a `std::byte` array, and its note points to `malloc` and its relatives, `memcpy`/`memmove`, `bit_cast`, `start_lifetime_as` and `allocator_traits::allocate`. `dma_allocate_aligned` is on none of these lists.")
rep("""// [class.prop]). Such objects come into existence only through a short list
// of operations: a call of a function named operator new or operator new[],
// std::malloc and its relatives, std::memcpy and std::memmove, std::bit_cast,
// and starting the lifetime of an unsigned char or std::byte array
// ([intro.object]). Each of them creates, in the memory it hands back or
// fills, the objects that the program goes on to use.
//
// dma_allocate_aligned is not on that list. It is an ordinary function, so
// the memory it returns holds no objects. A cast of that memory to kv_block*""",
"""// [class.prop]). Objects that no code constructs come into existence only
// through a short list of operations: a call of a function named operator new
// or operator new[], std::malloc and its relatives, std::memcpy and
// std::memmove, std::bit_cast, std::start_lifetime_as (C++23), and starting
// the lifetime of an unsigned char or std::byte array ([intro.object] and the
// note there). Each of them creates, in its own region of storage (the memory
// it returns, the destination it fills, or the byte array itself), the objects
// that the program goes on to use.
//
// dma_allocate_aligned is not on that list. It is an ordinary function that
// calls none of them, so the memory it returns holds no objects. A cast of
// that memory to kv_block*""")
rep('a("<h3>The reworded Note (as it stands after commits 2ebc426f3d and the r2 trim)</h3>")','a("<h3>The reworded Note (final proposed text)</h3>")')
rep('("implicit-lifetime type, object creation", "A C++ type that an allocation may create without a constructor call: scalars, arrays, and classes with a trivial constructor and destructor.',
    '("implicit-lifetime type, object creation", "A C++ type that an allocation may create without a constructor call: scalars, arrays, aggregates without a user-provided destructor, and classes with a trivial constructor and destructor.')
rep('        ("8-lane, 16-lane",','        ("AMX, AVX, SIMD, DMA, bf16, fp32, fp16", "AMX (Intel Advanced Matrix Extensions) and AVX (Advanced Vector Extensions, AVX2 = 256-bit, AVX-512 = 512-bit) are CPU instruction sets. SIMD (single instruction, multiple data) means one instruction works on a whole register of values. DMA (direct memory access) memory is memory the accelerator cards can read directly. bf16 is the 16-bit brain floating-point number format. fp32 and fp16 are the 32-bit and 16-bit IEEE float formats."),\n        ("analyst, refuter, critic", "Roles of the agents in the workflow that produced this page (section 14). One analyst per comment gathered the facts. Three refuters per analyst tried to disprove them. One critic checked completeness. \\"A refuter found X\\" means the fact came from that check."),\n        ("claude-box, nix, GCP Nix lane, people-check", "claude-box is the container this page was written from. Nix is the package manager that provides tron\'s build toolchain. The GCP Nix lane is the CI job that builds and tests tron with that toolchain on Google Cloud hosts. It builds AMX-off only. people-check is our script that reports whether delphi-3bda holds a CI lease or another user\'s jobs."),\n        ("8-lane, 16-lane",')
rep('("lcheck, clang-format, lint-notes", "lcheck is a syntax-only clang 19 compile on claude-box with the product\'s flags.','("lcheck, clang-format, lint-notes", "lcheck is a syntax-only clang 19 compile on claude-box with the product\'s flags (no code generation, no link).')
rep('a("<li>The paragraph at kv_cache.hpp:1459-1462 names three reads. All three exist at c73e7fb2f9: scaled_v_expr keeps a <code>const bf16s*</code> member and casts a bf16 pointer to it [:2233, :2326, :2400]; fill_storage_slot walks one bf16 pointer across K and V [:1652-1654]; the 8-lane accessors read a <code>bf16s v[page_size][head_size / chunk_size]</code> array as bf16 [:2462, :1961, :1969].</li>")',
    'a("<li>The paragraph at kv_cache.hpp:1459-1462 names three reads. All three exist at c73e7fb2f9:<ul><li>scaled_v_expr keeps a <code>const bf16s*</code> member and casts a bf16 pointer to it [:2233, :2326, :2400].</li><li>fill_storage_slot walks one bf16 pointer across K and V [:1652-1654].</li><li>The 8-lane accessors read a <code>bf16s v[page_size][head_size / chunk_size]</code> array as bf16 [:2462, :1961, :1969].</li></ul></li>")')
rep('After it the file holds no reinterpret_cast to or from bf16: scaled_v_expr::data becomes <code>const bf16*</code> and every tile address is computed in bf16 units; fill_storage_slot fills k and v as two arrays (v through detail::v_vnni_access::plane at 16 lanes); the 8-lane v becomes <code>bf16 v[page_size * head_size]</code> and the accessors build their views without a cast; the 8-lane scaled_v_expr loads each chunk with memcpy into a local bf16s. The paragraph is replaced by three lines that state the new rule.</li>',
    'After it the file holds no reinterpret_cast to or from bf16:<ul><li>scaled_v_expr::data becomes <code>const bf16*</code>, and every tile address is computed in bf16 units.</li><li>fill_storage_slot fills k and v as two arrays (v through detail::v_vnni_access::plane at 16 lanes).</li><li>The 8-lane v becomes <code>bf16 v[page_size * head_size]</code>, and the accessors build their views without a cast.</li><li>The 8-lane scaled_v_expr loads each chunk with memcpy into a local bf16s.</li></ul>The paragraph is replaced by three lines that state the new rule.</li>')
rep('Cursor Bugbot\'s summary says \\"Medium Risk\\" for the same reason.','Cursor Bugbot (an automated code-review bot that comments on GitHub PRs) rates the PR \\"Medium Risk\\" for the same reason.')
rep('it is his code with green CI, and the merge onto #4697 is conflict-free. The r2 build on 3bda (section 10) is the AMX-on test that his CI lane cannot give.','it is his code, its CI checks pass, and the merge onto #4697 is conflict-free. The r2 build on 3bda (section 10) is the AMX-on test that his CI lane cannot give.')
rep("""Agreed. A ticket already exists: #4588 (filed 2026-09-24, label Tech Debt, assigned to me). It covers these three reads and nothing else:

- the rule each read breaks,
- why clang 19 compiles them correctly today (vector accesses are tagged as possibly overlapping anything, and pointer steps are compiled to byte offsets),
- that no warning or sanitizer in our build detects them,
- the fix options.""","""Agreed. A ticket already exists: #4588 (filed 2026-09-24, label Tech Debt, assigned to me). It covers these three reads and nothing else. For each read it records:

- the rule the read breaks,
- why clang 19 compiles it correctly today (vector accesses are tagged as possibly overlapping anything, and pointer steps are compiled to byte offsets),
- that no warning or sanitizer in our build detects it,
- the fix options.""")
rep("""You also opened #4698 against this branch. This comment does not mention it, so I want to check that it is meant for this PR. I read it. It removes all three reads and this paragraph. A script compared the old and new load addresses for head_size 64, 128, 256 and 512 in both lane widths, and all are equal. All 21 CI checks on #4698 pass. On our Intel machine the four unit tests pass on the AMX-on and AMX-off builds with #4697 and #4698 applied together (<R2 COUNTS>).

My plan: merge #4698 into this branch as a merge commit, then close #4588 with a pointer to that commit. One gap stays on record: no CI job builds the 8-lane configuration, and the 8-lane `t_llama_unit` has 131 errors before this change (#4588, none of them in kv_cache.hpp). So the 8-lane hunks are checked by reading, not by a build.

Do you want #4698 merged into this PR, or landed separately after this PR merges?""","""You also opened #4698 against this branch. This comment does not mention it, so I checked whether it fits here. I read it. It removes all three reads and this paragraph. A script compared the old and new load addresses for head_size 64, 128, 256 and 512 in both lane widths, and all are equal. All 21 CI checks on #4698 pass. <R2 SENTENCE>

I merged #4698 into this branch as merge commit <MERGE_COMMIT> and closed #4588 with a pointer to it. One gap stays on record: no CI job builds the 8-lane configuration, and the 8-lane `t_llama_unit` has 131 errors before this change (#4588, none of them in kv_cache.hpp). So the 8-lane hunks are checked by reading, not by a build.

If you meant #4698 to land separately after this PR merges, say so and I will drop the merge commit before the next push.""")
rep("It covers exactly these three reads: the rule each one breaks, why clang 19 compiles them correctly today, that no warning or sanitizer in our build detects them, and the fix options. Commit <SHA>","It covers exactly these three reads. For each one it records the rule it breaks, why clang 19 compiles it correctly today, that no warning or sanitizer in our build detects it, and the fix options. Commit <SHA>")
rep('Draft closing comment for issue #4588 (option d; fill in the merge commit)</div>','Draft closing comment for issue #4588 (option d; fill in the merge commit and the r2 test counts from section 10)</div>')
rep('His later straw-man sketch said','His later sketch (a proposal he posted for discussion) said')
rep('The design\'s Q3 chose operator[] logical rows','Q3 (question 3 of the design page status/design-new-tensor-type.html) chose operator[] logical rows')
rep('and the packed-K child repeats the cost once.','and the packed-K child (the planned follow-on PR that gives K the same packed layout) repeats the cost once.')
rep('all point the same way, and the PR 4424 child','all favor dropping it, and the PR 4424 child')
rep("Your later straw-man sketch had `at()` only and no `operator[]` (comment 5765866077).","Your later sketch had `at()` only and no `operator[]` (comment 5765866077).")
rep("Net -109 lines in 4 files. No production path changes. The diff applies cleanly and passes a syntax-only compile at 16 lanes. I would build and test it at 16 lanes (AVX-512) and 8 lanes (AVX2) before pushing.","Net -109 lines in 3 files, plus one comment line to adjust in kv_cache.hpp. No production path changes. The diff applies cleanly and passes a syntax-only compile at 16 lanes. I would build and test it at 16 lanes (AVX-512) and run a syntax-only compile at 8 lanes (AVX2) before pushing. t_llama_unit does not build at 8 lanes today (#4588), so a full 8-lane test is not possible yet.")
rep('The helpers sit outside the <code>#if TRON_CHUNK_SIZE == 16</code> block, so every build parses them; only the 16-lane build instantiates them.','The helpers sit outside the <code>#if TRON_CHUNK_SIZE == 16</code> block, so every build parses them. Only the 16-lane build instantiates them.')
rep('Keeps his commit id and authorship, and GitHub should mark #4697 merged (not exercised here; fallback: close it with a note).','Keeps his commit id and authorship. GitHub should mark #4697 merged (not exercised here. Fallback: close it with a note).')
rep('I built your commit with the AMX kernels on our Intel machine','I built your change (cherry-picked onto this branch, same content as 8bbbb7c82d) with the AMX kernels on our Intel machine')
rep('people-check said FREE both times','people-check (defined under Words used here) said FREE both times')
rep('a("<p>Line numbers refer to the body as fetched on 2026-09-30 (exec/ben-20260930/../../status is not the source; the live body is). Re-fetch before editing.</p>")','a("<p>Line numbers refer to the body as fetched on 2026-09-30. The live GitHub body is the source, not any copy on disk. Re-fetch before editing.</p>")')
rep('"Performance of the 16-lane scaled_v_expr after #4698. Same intrinsics, same addresses by enumeration, codegen not compared at page-generation time (the r2 run includes an objdump comparison of the scaled_v_expr functions in t_llama_unit; see section 10 once it reports). The #4698 CI benchmark','"Performance of the 16-lane scaled_v_expr after #4698. Same intrinsics, same addresses by enumeration. The generated machine code comparison is part of the r2 run (an objdump comparison of the scaled_v_expr functions in t_llama_unit, section 10). The #4698 CI benchmark')
rep('"Whether GitHub marks #4697 merged after a fast-forward push. Standard behaviour, not exercised.','"Whether GitHub marks #4697 merged after a fast-forward push. Standard behavior, not exercised.')
rep('(the merge base, called \\"main\\" here; origin/main has since moved to 43e533f7b6 with kv_cache.hpp byte-identical)','(the merge base, called \\"main\\" here. origin/main has since moved to 43e533f7b6, with kv_cache.hpp byte-identical)')
rep("All six comments hold in substance, and four of them (the Note rename, the Note reword, the tracker link, and the reviewer\\'s own helper PR #4697) are already applied on a scratch branch and pass the four unit tests on delphi-3bda in the AMX-on and AMX-off builds. Two need an answer from jhan or the reviewer: the enum flags (a follow-up issue, drafted below) and whether to keep or drop <code>v_vnni_row</code> (I lean to drop). One thing the comments do not say: the reviewer also opened PR #4698 against this branch, which removes the three non-ISO reads that comment B4 asks a ticket for, so the recommended answer to B4 is to merge #4698 and close issue #4588.",
    "All six comments hold in substance. Four of them (the Note rename, the Note reword, the tracker link, and the reviewer\\'s own helper PR #4697) are applied on a scratch branch and pass the four unit tests on delphi-3bda (our Intel test machine) in the AMX-on and AMX-off builds. Three need a decision by jhan or the reviewer: the enum flags (B1, a follow-up issue is drafted below), keep or drop <code>v_vnni_row</code> (B5, I lean to drop), and B4, where the reviewer also opened PR #4698 that removes the three non-ISO reads he asks a ticket for, so I recommend merging #4698 and closing issue #4588.")
# r2-dependent wording in figure 1
rep('Proposed end state of jhan-kv-typed-tensors (verified on the scratch branch ben-r2)','Proposed end state of jhan-kv-typed-tensors (built on the scratch branch ben-r2, section 10)')
rep('Bottom: the proposed branch after the round, as built and tested on the scratch branch ben-r2 (section 10).','Bottom: the proposed branch after the round, as built on the scratch branch ben-r2 (section 10 has its test status).')
# r2 sentence handling
rep('''    for k in ("B4", "B6"):
        REPLIES[k] = REPLIES[k].replace("<R2 COUNTS>", r2_counts_sentence)''','''    r2_sentence = ("On our Intel machine the four unit tests pass on the AMX-on and AMX-off builds with #4697 and #4698 applied together (" + r2_counts_sentence + ")."
                   if r2_done else "<R2 RESULT: pending. When the r2 run reports a pass, write: On our Intel machine the four unit tests pass on the AMX-on and AMX-off builds with #4697 and #4698 applied together (counts). If it fails, say so instead.>")
    REPLIES["B4"] = REPLIES["B4"].replace("<R2 SENTENCE>", r2_sentence)''')
open(p,'w').write(s); print('replacements', n)
